{% set name = "editdistance" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/roy-ht/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bc58aac72b82bcc22f15d70423990a568c28fda32392fa0eeba66a288e7b5a19
  patches:
    # add python 3.11 compat patch: https://github.com/roy-ht/editdistance/commit/5c81574c1ea9538a4d9c97d1f9c28cc10d67980f
    - patches/0001-cythonize.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch  # [unix]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
  run:
    - python

test:
  source_files:
    - test
  imports:
    - editdistance
  commands:
    - python test/test_editdistance.py
    - pip check
  requires:
    - pip

about:
  home: https://github.com/roy-ht/editdistance
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast implementation of the edit distance(Levenshtein distance)
  description: Fast implementation of the edit distance(Levenshtein distance)
  doc_url: https://github.com/roy-ht/editdistance
  dev_url: https://github.com/roy-ht/editdistance

extra:
  recipe-maintainers:
    - cbouss
