{% set name = "editdistance" %}
{% set version = "0.5.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "5a51276aaa6be65c2ac0fb807af93267b4f2488662fc925d27c4d317ef5d067a" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  source_files:
    - test
  imports:
    - editdistance
  commands:
    - python test/test_editdistance.py

about:
  home: https://www.github.com/aflc/editdistance
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Fast implementation of the edit distance(Levenshtein distance)'
  description: "Fast implementation of the edit distance(Levenshtein distance)"
  doc_url: https://github.com/aflc/editdistance
  dev_url: https://github.com/aflc/editdistance

extra:
  recipe-maintainers:
    - nelson-liu
