# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NWzqO1qa061GFA1dnawZqVkT4qGvj4Ljt0M6OzOTW9qe98AFow/G6CqrimbX8Ml/BgrJdarr3XSPg4RKm/o3ud1a/ohcRZV2f3PdhijNKnbrVQLRCPZ+D6hODat00lxV/uDkTjFe4aIkVRarAMy48YW2cihGZQsvkn3xkfHgrG1eUWC8WJk/6WCC+a1bl0u7KpqPZD5UhKueTzqqQt1kzai5ZO0Tvo8+4VAitA3IUw92R/i+mFoGb18ykwpVKNP50H52rhgh5ZH6i9fSM7rKepp1D7202O7RJx0T/mlifrTCnPYompkRPTMi8DRe6GP/y000rK72ohapeGyAgTrz2exsYgXKcd3An3fPtmlWtfsiz7w/DtV2sSXKifJmqXZF1dPhH6TWU/fbHtKPty/wYPtE5uVBb+HGgTl54Sr5ZVUV5QhNEneeMAwfwBqdCVkd/4iNBIZLg5Nrlb5d0WKxyVDGb+Y1Hhg3mCGM71poMMJdjPkUeYSPac3S9FrrZk/raKLkSqJ4YDaJe8n5EKNAKKVaM3qL4sze0N2/wIN1MyQoHBFtkt8jEUK/yP+ixwSzLzhqapyps4BV98oF/vGnP0zJliU2LnVh1Jx2Q6I9nBsPBmwdGAuuQOF/qr9ZR78kWC4/gNrSTWi/o+3b9ykB0qPYX8I3Z+dKjF1LmFcVJag="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
