travis:
  secure:
    BINSTAR_TOKEN: NWzqO1qa061GFA1dnawZqVkT4qGvj4Ljt0M6OzOTW9qe98AFow/G6CqrimbX8Ml/BgrJdarr3XSPg4RKm/o3ud1a/ohcRZV2f3PdhijNKnbrVQLRCPZ+D6hODat00lxV/uDkTjFe4aIkVRarAMy48YW2cihGZQsvkn3xkfHgrG1eUWC8WJk/6WCC+a1bl0u7KpqPZD5UhKueTzqqQt1kzai5ZO0Tvo8+4VAitA3IUw92R/i+mFoGb18ykwpVKNP50H52rhgh5ZH6i9fSM7rKepp1D7202O7RJx0T/mlifrTCnPYompkRPTMi8DRe6GP/y000rK72ohapeGyAgTrz2exsYgXKcd3An3fPtmlWtfsiz7w/DtV2sSXKifJmqXZF1dPhH6TWU/fbHtKPty/wYPtE5uVBb+HGgTl54Sr5ZVUV5QhNEneeMAwfwBqdCVkd/4iNBIZLg5Nrlb5d0WKxyVDGb+Y1Hhg3mCGM71poMMJdjPkUeYSPac3S9FrrZk/raKLkSqJ4YDaJe8n5EKNAKKVaM3qL4sze0N2/wIN1MyQoHBFtkt8jEUK/yP+ixwSzLzhqapyps4BV98oF/vGnP0zJliU2LnVh1Jx2Q6I9nBsPBmwdGAuuQOF/qr9ZR78kWC4/gNrSTWi/o+3b9ykB0qPYX8I3Z+dKjF1LmFcVJag=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
