travis:
  secure:
    BINSTAR_TOKEN: U2ZwJOf6thmsD2ZP8/rQQZB66X+uKf1pQTSrBuFWSUOABvY4PW+ICGeZNz67aAkU4YufBnAEvU8EyrA52hHrdAbKXbGHWUaZT16e75LGMyhklvOIzGblJSooWllzfHWFv6oeVeGtGxqsbrjypeolmm8A3vtNFFHF6FgEcXnoMMbZ8YQo6fJ6az9T3IeBY6LSuHZtEeINj0Cf7qwE8AHlLt5HSLewjKPWSFqS+10UpccvTiCmAzwJCg+6dTXBDKovO1OL67qRMwwq/OMtu5vsI6EXTThqy2D26T5khcZ8h+ib+D5i2AsPwgALJwQVcfNLsphPNFej7ZGeNVpcBf5YBpTr3q+ry8AmCwoQdaeeAc4KQGKaqtvg8ofDN+p1DSVU8Isrt8Qs9CMJmUBFbqSXQdS8zUFAFOOlOHxLkl1Sl5csp3x8UzkUpsyBobTRbUuMszsoiUem0tzbGCdFZOHm4Erbz5I1Q0qZgWuu/nZ1UypmDeCmBo/x3cO9dogIlANf5Bu6G5pEfUPEZj3fwwxqg7+QRrENckTBpEHr0gxiUe8P64j+7+3JXeJmdDYLB/ywGOn7+QRnPEZi/HFYDI7YddYCJlbcfNHEMTfIF2uWiEjTrs8lr96+5JCncDFnthQYG558iHwQ1JCBefkTcil4ds+8Fy4wsyzh3XjdAB14YTo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
